export interface Env { DB: D1Database; RECEIPTS: R2Bucket; API_TOKEN: string }
const json = (data: unknown, status = 200) => Response.json(data, { status, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, Authorization' } })
const id = () => crypto.randomUUID()
async function balances(db: D1Database, tripId: string) {
  const { results } = await db.prepare(`SELECT u.id, u.display_name, COALESCE(SUM(CASE WHEN e.payer_user_id=u.id THEN e.amount ELSE 0 END),0)-COALESCE((SELECT SUM(share_amount) FROM expense_shares s JOIN expenses x ON x.id=s.expense_id WHERE s.user_id=u.id AND x.trip_id=? AND x.deleted_at IS NULL),0) net FROM trip_members m JOIN users u ON u.id=m.user_id LEFT JOIN expenses e ON e.trip_id=m.trip_id AND e.payer_user_id=u.id AND e.deleted_at IS NULL WHERE m.trip_id=? GROUP BY u.id`).bind(tripId,tripId).all<{id:string;display_name:string;net:number}>()
  const creditors = results.filter(x=>x.net>0).map(x=>({...x})); const debtors = results.filter(x=>x.net<0).map(x=>({...x,net:-x.net})); const settlements: unknown[]=[]
  while (creditors.length && debtors.length) { const c=creditors[0], d=debtors[0], amount=Math.min(c.net,d.net); settlements.push({from:{id:d.id,name:d.display_name},to:{id:c.id,name:c.display_name},amount}); c.net-=amount;d.net-=amount;if(!c.net)creditors.shift();if(!d.net)debtors.shift() }
  return settlements
}
export default { async fetch(request: Request, env: Env): Promise<Response> { if(request.method==='OPTIONS') return json({}); const url=new URL(request.url); const auth=request.headers.get('Authorization')===`Bearer ${env.API_TOKEN}`; if(url.pathname==='/admin/health') { if(!auth)return json({error:'Unauthorized'},401); try { await env.DB.prepare('SELECT 1').first(); const key=`health/${id()}`;await env.RECEIPTS.put(key,'ok');await env.RECEIPTS.delete(key);return json({d1:'ok',r2:'ok',sync:'ready'}) } catch { return json({d1:'failed',r2:'failed'},503) } }
  const balanceMatch=url.pathname.match(/^\/trips\/([^/]+)\/balances$/); if(request.method==='GET'&&balanceMatch)return json({balances:await balances(env.DB,balanceMatch[1])});
  if(request.method==='POST'&&url.pathname==='/sync/push') { const body=await request.json<{expenses?:{id:string;trip_id:string;payer_user_id:string;amount:number;currency:string;description:string;updated_at:string}[]}>(); const writes=(body.expenses||[]).map(e=>env.DB.prepare('INSERT INTO expenses (id,trip_id,payer_user_id,amount,currency,description,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET amount=excluded.amount,description=excluded.description,updated_at=excluded.updated_at WHERE excluded.updated_at > expenses.updated_at').bind(e.id,e.trip_id,e.payer_user_id,e.amount,e.currency,e.description,e.updated_at)); await env.DB.batch(writes); return json({accepted:writes.length}) }
  if(request.method==='POST'&&url.pathname==='/sync/pull') { const since=url.searchParams.get('since')||'1970-01-01'; const changes=await env.DB.prepare('SELECT * FROM expenses WHERE updated_at>?').bind(since).all(); return json({changes:changes.results,server_time:new Date().toISOString()}) }
  return json({error:'Not found'},404) } }
