import { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Bell, ChevronDown, CreditCard, LayoutDashboard, Map, MoreHorizontal, Plus, ReceiptText, Settings, Users, WalletCards } from 'lucide-react'
import './styles.css'

type Expense = { id: number; title: string; category: string; payer: string; amount: number; date: string; split: string; color: string }
const initialExpenses: Expense[] = [
  { id: 1, title: 'Harborview Hotel', category: 'Stay', payer: 'You', amount: 642, date: 'Jun 14', split: 'Split equally', color: '#7959e8' },
  { id: 2, title: 'Dinner at Kismet', category: 'Food', payer: 'Maya', amount: 168.50, date: 'Jun 15', split: 'Split equally', color: '#e19d55' },
  { id: 3, title: 'Kayak rental', category: 'Activities', payer: 'You', amount: 96, date: 'Jun 16', split: 'Maya, Theo', color: '#4cae9d' },
  { id: 4, title: 'Airport transfer', category: 'Transport', payer: 'Theo', amount: 54, date: 'Jun 17', split: 'Split equally', color: '#e46973' },
]
const people = [{ name: 'You', initials: 'AL', color: '#8d6cea' }, { name: 'Maya Chen', initials: 'MC', color: '#ef9f71' }, { name: 'Theo Grant', initials: 'TG', color: '#63b6a6' }]
function Avatar({ person }: { person: typeof people[number] }) { return <span className="avatar" style={{ background: person.color }}>{person.initials}</span> }
function App() {
 const [expenses, setExpenses] = useState(initialExpenses); const [showModal, setShowModal] = useState(false); const [active, setActive] = useState('Overview')
 const total = useMemo(() => expenses.reduce((sum, x) => sum + x.amount, 0), [expenses])
 const addExpense = (form: FormData) => { const title = String(form.get('title') || 'New expense'); const amount = Number(form.get('amount')) || 0; setExpenses([{ id: Date.now(), title, category: String(form.get('category')), payer: 'You', amount, date: 'Today', split: 'Split equally', color: '#5d8dea' }, ...expenses]); setShowModal(false) }
 const nav = [{ icon: LayoutDashboard, label: 'Overview' }, { icon: Map, label: 'Trips' }, { icon: ReceiptText, label: 'Expenses' }, { icon: WalletCards, label: 'Settlements' }]
 return <div className="app-shell">
  <aside><div className="brand"><span className="brand-mark">r</span><span>roamwise</span></div><nav>{nav.map(({icon: Icon,label}) => <button onClick={() => setActive(label)} className={active === label ? 'selected' : ''} key={label}><Icon size={19}/>{label}</button>)}</nav><div className="side-bottom"><button><Users size={19}/>People</button><button><Settings size={19}/>Settings</button><div className="profile"><Avatar person={people[0]}/><span><b>Alex Lee</b><small>Personal workspace</small></span><MoreHorizontal size={18}/></div></div></aside>
  <main><header><div className="crumb"><span>Trips</span><i>/</i><b>Portugal escape</b><ChevronDown size={16}/></div><div className="header-actions"><button className="icon-btn"><Bell size={19}/><em/></button><button className="invite"><Users size={17}/>Invite</button><button className="add" onClick={() => setShowModal(true)}><Plus size={18}/>Add expense</button></div></header>
  <section className="hero"><div><div className="eyebrow">PORTUGAL · JUNE 14–21, 2025</div><h1>Portugal escape</h1><p>Lisbon, Sintra & the Algarve <span>·</span> 3 travellers</p></div><div className="travellers">{people.map(p=><Avatar person={p} key={p.name}/>)}<button><Plus size={15}/></button></div></section>
  <section className="metrics"><article><span>Total trip spend</span><strong>${total.toLocaleString('en-US',{minimumFractionDigits:2})}</strong><small><b>12</b> expenses this trip</small></article><article><span>Your total paid</span><strong>$738.00</strong><small className="blue">↑ $96.00 <i>since yesterday</i></small></article><article><span>Your balance</span><strong className="positive">You are owed $142.33</strong><small className="positive-dot">Up to date</small></article></section>
  <section className="content-grid"><div className="panel expenses"><div className="panel-head"><div><h2>Recent expenses</h2><p>Everything added to this trip</p></div><button className="text-button" onClick={()=>setActive('Expenses')}>View all</button></div><div className="table-head"><span>EXPENSE</span><span>PAID BY</span><span>AMOUNT</span></div>{expenses.map(e=><div className="expense-row" key={e.id}><div className="expense-title"><span className="expense-icon" style={{background:e.color}}>{e.category[0]}</span><span><b>{e.title}</b><small>{e.category} · {e.date} · {e.split}</small></span></div><div className="payer"><Avatar person={people.find(p=>p.name===e.payer) || people[0]}/>{e.payer}</div><b>${e.amount.toLocaleString('en-US',{minimumFractionDigits:2})}</b><MoreHorizontal size={18}/></div>)}</div>
  <div className="right-column"><div className="panel settle"><div className="panel-head"><div><h2>Settle up</h2><p>Suggested payments</p></div><button className="dots"><MoreHorizontal size={18}/></button></div><div className="settle-person"><Avatar person={people[1]}/><div><b>You owe Maya</b><small>For meals and tickets</small></div><strong>$25.17</strong></div><button className="settle-button"><CreditCard size={17}/>Settle with Maya</button><div className="divider"/><div className="settle-person"><Avatar person={people[2]}/><div><b>Theo owes you</b><small>For accommodation</small></div><strong className="green">$167.50</strong></div><button className="remind">Send Theo a reminder</button></div><div className="panel activity"><h2>Trip activity</h2><div><span className="timeline-dot"/><p><b>Maya</b> added Dinner at Kismet<br/><small>Today at 10:42 AM</small></p></div><div><span className="timeline-dot purple"/><p><b>You</b> added Kayak rental<br/><small>Yesterday at 4:18 PM</small></p></div></div></div></section></main>
  {showModal && <div className="modal-backdrop"><form className="modal" action={addExpense}><button type="button" className="close" onClick={()=>setShowModal(false)}>×</button><div className="modal-icon"><ReceiptText size={22}/></div><h2>Add an expense</h2><p>We'll split it equally with your tripmates.</p><label>What was it?<input name="title" autoFocus placeholder="e.g. Train to Sintra" required/></label><label>Amount<input name="amount" type="number" step="0.01" placeholder="0.00" required/></label><label>Category<select name="category"><option>Food</option><option>Transport</option><option>Stay</option><option>Activities</option></select></label><button className="add full">Save expense</button></form></div>}</div>
}
createRoot(document.getElementById('root')!).render(<App />)
