import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Bell, CalendarDays, Check, ChevronDown, Cloud, CloudOff, CreditCard, Download, LayoutDashboard, MapPin, MoreHorizontal, Plus, ReceiptText, Settings, Users, WalletCards } from 'lucide-react'
import './styles.css'

type Role = 'owner' | 'editor' | 'viewer'
type Person = { id: string; name: string; initials: string; color: string; role: Role }
type Expense = { id: string; title: string; category: string; payerId: string; amount: number; currency: string; date: string; participantIds: string[]; updatedAt: number }
type ItineraryItem = { id: string; day: number; time: string; title: string; kind: 'flight' | 'stay' | 'activity' | 'free'; notes?: string; participantIds: string[] }
type PackingItem = { id: string; category: string; title: string; assignedTo: string[]; checked: boolean; custom?: boolean }
type Trip = { id: string; name: string; startDate: string; endDate: string; locations: string; members: Person[]; expenses: Expense[]; itinerary: ItineraryItem[]; packing: PackingItem[]; updatedAt: number }
const CLOUD_EDITOR_PRIORITY_MS = 30_000
const key = 'roamwise-travel-planner-v2'
const people: Person[] = [{ id: 'alex', name: 'Alex Lee', initials: 'AL', color: '#8d6cea', role: 'owner' }, { id: 'maya', name: 'Maya Chen', initials: 'MC', color: '#ef9f71', role: 'editor' }, { id: 'theo', name: 'Theo Grant', initials: 'TG', color: '#63b6a6', role: 'viewer' }]
const template: PackingItem[] = [['Documents', 'Passport'], ['Documents', 'Travel insurance'], ['Electronics', 'Phone charger'], ['Electronics', 'Power adapter'], ['Clothing', 'Swimwear']].map(([category, title], i) => ({ id: `p${i}`, category, title, assignedTo: ['alex'], checked: false }))
const freshTrip = (): Trip => ({ id: 'portugal-2025', name: 'Portugal escape', startDate: '2025-06-14', endDate: '2025-06-21', locations: 'Lisbon, Sintra & the Algarve', members: people, updatedAt: Date.now(), packing: template, itinerary: [
 { id: 'i1', day: 1, time: '09:30', title: 'Flight TP 202 · Newark to Lisbon', kind: 'flight', participantIds: ['alex', 'maya', 'theo'] }, { id: 'i2', day: 1, time: '16:00', title: 'Check in · Harborview Hotel', kind: 'stay', participantIds: ['alex', 'maya', 'theo'] }, { id: 'i3', day: 2, time: '10:00', title: 'Pastéis de Belém & riverside walk', kind: 'activity', participantIds: ['alex', 'maya'] }, { id: 'i4', day: 2, time: '15:00', title: 'Free time', kind: 'free', participantIds: ['alex', 'maya', 'theo'] },
], expenses: [
 { id: 'e1', title: 'Harborview Hotel', category: 'Stay', payerId: 'alex', amount: 642, currency: 'USD', date: 'Jun 14', participantIds: ['alex', 'maya', 'theo'], updatedAt: Date.now() }, { id: 'e2', title: 'Dinner at Kismet', category: 'Food', payerId: 'maya', amount: 168.5, currency: 'USD', date: 'Jun 15', participantIds: ['alex', 'maya', 'theo'], updatedAt: Date.now() }, { id: 'e3', title: 'Kayak rental', category: 'Activities', payerId: 'alex', amount: 96, currency: 'USD', date: 'Jun 16', participantIds: ['maya', 'theo'], updatedAt: Date.now() }, { id: 'e4', title: 'Airport transfer', category: 'Transport', payerId: 'theo', amount: 54, currency: 'USD', date: 'Jun 17', participantIds: ['alex', 'maya', 'theo'], updatedAt: Date.now() }
] })
function normTrip(value: unknown): Trip { const base = freshTrip(); if (!value || typeof value !== 'object') return base; const t = value as Partial<Trip>; return { ...base, ...t, members: Array.isArray(t.members) ? t.members : base.members, expenses: Array.isArray(t.expenses) ? t.expenses : base.expenses, itinerary: Array.isArray(t.itinerary) ? t.itinerary : base.itinerary, packing: Array.isArray(t.packing) ? t.packing : base.packing } }
function usePersist<T>(storageKey: string, fallback: T) { const [value, setValue] = useState<T>(() => { try { const raw = localStorage.getItem(storageKey); return raw ? JSON.parse(raw) : fallback } catch { return fallback } }); useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(value)) }, [storageKey, value]); return [value, setValue] as const }
function getCloudDeviceId() { const k = 'roamwise-device-id'; let id = localStorage.getItem(k); if (!id) { id = crypto.randomUUID(); localStorage.setItem(k, id) } return id }
async function fetchCloudWorkerPayload(url: string, trip: Trip) { const response = await fetch(`${url.replace(/\/$/, '')}/sync/push`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ deviceId: getCloudDeviceId(), updatedAt: trip.updatedAt, trip }) }); if (!response.ok) throw new Error('Cloud sync failed') }
function calcDuration(start: string, end: string) { return Math.round((Date.parse(end) - Date.parse(start)) / 86_400_000) + 1 }
function tripCountdownLabel(start: string) { const days = Math.round((Date.parse(start) - Date.now()) / 86_400_000); return days >= 0 ? `${days} days to go` : `${Math.abs(days)} days ago` }
function settlementLines(expenses: Expense[], members: Person[]) { const net = Object.fromEntries(members.map(p => [p.id, 0])); expenses.forEach(e => { net[e.payerId] += e.amount; const share = e.amount / e.participantIds.length; e.participantIds.forEach(id => net[id] -= share) }); const creditors = members.filter(p => net[p.id] > .01).map(p => ({ ...p, amount: net[p.id] })); const debtors = members.filter(p => net[p.id] < -.01).map(p => ({ ...p, amount: -net[p.id] })); const lines: { from: Person; to: Person; amount: number }[] = []; while (creditors.length && debtors.length) { const c = creditors[0], d = debtors[0], amount = Math.min(c.amount, d.amount); lines.push({ from: d, to: c, amount }); c.amount -= amount; d.amount -= amount; if (c.amount < .01) creditors.shift(); if (d.amount < .01) debtors.shift() } return lines }
function Avatar({ person }: { person: Person }) { return <span className="avatar" title={person.name} style={{ background: person.color }}>{person.initials}</span> }
function App() {
 const [trip, setRawTrip] = usePersist<Trip>(key, freshTrip()); const [active, setActive] = useState('Overview'); const [modal, setModal] = useState<'expense' | 'item' | null>(null); const [cloudUrl, setCloudUrl] = usePersist('roamwise-cloud-url', ''); const [syncState, setSyncState] = useState<'local' | 'syncing' | 'synced' | 'error'>('local'); const tripData = normTrip(trip); const current = tripData.members[0]; const canEditItinerary = current.role !== 'viewer'; const setTrip = (fn: (t: Trip) => Trip) => setRawTrip(prev => ({ ...fn(normTrip(prev)), updatedAt: Date.now() }));
 const total = useMemo(() => tripData.expenses.reduce((sum, x) => sum + x.amount, 0), [tripData.expenses]); const lines = useMemo(() => settlementLines(tripData.expenses, tripData.members), [tripData]); const days = calcDuration(tripData.startDate, tripData.endDate);
 async function sync() { if (!cloudUrl) return; setSyncState('syncing'); try { await fetchCloudWorkerPayload(cloudUrl, tripData); setSyncState('synced') } catch { setSyncState('error') } }
 function addExpense(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const ids = form.getAll('split').map(String); setTrip(t => ({ ...t, expenses: [{ id: crypto.randomUUID(), title: String(form.get('title')), category: String(form.get('category')), payerId: 'alex', amount: Number(form.get('amount')), currency: String(form.get('currency')), date: 'Today', participantIds: ids.length ? ids : ['alex'], updatedAt: Date.now() }, ...t.expenses] })); setModal(null) }
 function addItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); setTrip(t => ({ ...t, itinerary: [...t.itinerary, { id: crypto.randomUUID(), title: String(f.get('title')), day: Number(f.get('day')), time: String(f.get('time')), kind: 'activity', participantIds: ['alex'] }] })); setModal(null) }
 const nav = [{ icon: LayoutDashboard, label: 'Overview' }, { icon: CalendarDays, label: 'Itinerary' }, { icon: ReceiptText, label: 'Expenses' }, { icon: WalletCards, label: 'Settlements' }, { icon: Check, label: 'Packing' }]
 return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">r</span><span>roamwise</span></div><nav>{nav.map(({ icon: Icon, label }) => <button onClick={() => setActive(label)} className={active === label ? 'selected' : ''} key={label}><Icon size={19}/>{label}</button>)}</nav><div className="side-bottom"><button onClick={() => setActive('People')}><Users size={19}/>People</button><button onClick={() => setActive('Settings')}><Settings size={19}/>Settings</button><div className="profile"><Avatar person={current}/><span><b>Alex Lee</b><small>Personal workspace</small></span><MoreHorizontal size={18}/></div></div></aside><main>
 <header><div className="crumb"><span>Trips</span><i>/</i><b>{tripData.name}</b><ChevronDown size={16}/></div><div className="header-actions"><button className="sync" onClick={sync} title="Sync with your Cloudflare Worker">{syncState === 'synced' ? <Cloud size={17}/> : <CloudOff size={17}/>} {syncState === 'syncing' ? 'Syncing…' : syncState === 'synced' ? 'Synced' : 'Cloud sync'}</button><button className="icon-btn"><Bell size={19}/><em/></button><button className="add" onClick={() => setModal(active === 'Itinerary' ? 'item' : 'expense')}><Plus size={18}/>{active === 'Itinerary' ? 'Add plan' : 'Add expense'}</button></div></header>
 <section className="hero"><div><div className="eyebrow">PORTUGAL · JUNE 14–21, 2025</div><h1>{tripData.name}</h1><p><MapPin size={14}/>{tripData.locations}<span>·</span>{days} days <span>·</span>{tripCountdownLabel(tripData.startDate)}</p></div><div className="travellers">{tripData.members.map(p => <Avatar person={p} key={p.id}/>)}<button><Plus size={15}/></button></div></section>
 {active === 'Overview' && <><section className="metrics"><article><span>Total trip spend</span><strong>${total.toLocaleString('en-US', { minimumFractionDigits: 2 })}</strong><small><b>{tripData.expenses.length}</b> expenses this trip</small></article><article><span>Trip progress</span><strong>{tripData.itinerary.length} plans</strong><small className="blue">{tripData.packing.filter(x => x.checked).length}/{tripData.packing.length} packed</small></article><article><span>Your balance</span><strong className="positive">{lines.find(x => x.to.id === 'alex') ? 'You are owed money' : 'All settled up'}</strong><small className="positive-dot">Up to date</small></article></section><section className="content-grid"><div className="panel"><PanelTitle title="Recent expenses" description="Everything added to this trip"/><ExpensePanel expenses={tripData.expenses.slice(0, 4)} members={tripData.members}/></div><div className="right-column"><div className="panel"><PanelTitle title="Settle up" description="Suggested optimized payments"/><SettlementPanel lines={lines}/></div><div className="panel weather"><div><Cloud size={18}/><b>Lisbon weather</b></div><strong>23°</strong><p>Sunny · ideal for a walk</p><small>Open-Meteo forecast ready</small></div></div></section></>}
 {active === 'Expenses' && <section className="panel page-panel"><PanelTitle title="Expense ledger" description="Multi-currency expenses and participant splits"/><ExpensePanel expenses={tripData.expenses} members={tripData.members}/></section>}
 {active === 'Settlements' && <section className="panel page-panel"><PanelTitle title="Settle up" description="Optimized payments after every shared expense"/><SettlementPanel lines={lines}/></section>}
 {active === 'Itinerary' && <section className="panel page-panel"><PanelTitle title="Itinerary" description="Flights, stays, optional stops, and shared free time"/>{Array.from({ length: days }, (_, i) => i + 1).map(day => <div className="day" key={day}><b>DAY {day}</b>{tripData.itinerary.filter(x => x.day === day).sort((a,b) => a.time.localeCompare(b.time)).map(item => <div className="itinerary" key={item.id}><time>{item.time}</time><span className={`type ${item.kind}`}/><div><b>{item.title}</b><small>{item.kind === 'free' ? `${item.participantIds.length} travellers available` : item.kind}</small></div></div>)}</div>)}</section>}
 {active === 'Packing' && <section className="panel page-panel"><PanelTitle title="Packing list" description="Shared essentials, assigned to each traveller"/>{['Documents', 'Electronics', 'Clothing'].map(category => <div className="packing-group" key={category}><b>{category}</b>{tripData.packing.filter(x => x.category === category).map(item => <label className="packing" key={item.id}><input type="checkbox" checked={item.checked} onChange={() => setTrip(t => ({ ...t, packing: t.packing.map(x => x.id === item.id ? { ...x, checked: !x.checked } : x) }))}/><span>{item.title}</span><small>{item.assignedTo.map(id => tripData.members.find(p => p.id === id)?.name).join(', ')}</small></label>)}</div>)}</section>}
 {active === 'Settings' && <section className="panel page-panel settings"><PanelTitle title="Trip settings" description="Permissions, profiles, and cloud synchronization"/><label>Cloudflare Worker URL<input value={cloudUrl} onChange={e => setCloudUrl(e.target.value)} placeholder="https://your-worker.workers.dev"/></label><button className="add" onClick={sync}><Cloud size={17}/>Save & sync</button><div className="roles">{tripData.members.map(p => <div key={p.id}><Avatar person={p}/><span><b>{p.name}</b><small>{p.role} · {p.role === 'viewer' ? 'view only' : 'can edit itinerary'}</small></span></div>)}</div><button className="export"><Download size={17}/>Export trip overview as PDF</button></section>}
 </main>{modal && <div className="modal-backdrop"><form className="modal" onSubmit={modal === 'expense' ? addExpense : addItem}><button type="button" className="close" onClick={() => setModal(null)}>×</button><div className="modal-icon">{modal === 'expense' ? <ReceiptText size={22}/> : <CalendarDays size={22}/>}</div><h2>{modal === 'expense' ? 'Add an expense' : 'Add to itinerary'}</h2><p>{modal === 'expense' ? 'Record a payment and choose who shares it.' : 'Create a shared plan for your trip.'}</p><label>{modal === 'expense' ? 'What was it?' : 'Plan name'}<input name="title" autoFocus required placeholder={modal === 'expense' ? 'e.g. Train to Sintra' : 'e.g. Sunset sailing'}/></label>{modal === 'expense' ? <><label>Amount<input name="amount" type="number" min="0" step="0.01" required placeholder="0.00"/></label><div className="form-grid"><label>Currency<select name="currency"><option>USD</option><option>EUR</option><option>HKD</option></select></label><label>Category<select name="category"><option>Food</option><option>Transport</option><option>Stay</option><option>Activities</option></select></label></div><fieldset><legend>Split with</legend>{tripData.members.map(p => <label key={p.id}><input type="checkbox" name="split" value={p.id} defaultChecked/>{p.name}</label>)}</fieldset></> : <div className="form-grid"><label>Day<select name="day">{Array.from({ length: days }, (_, i) => <option key={i} value={i + 1}>Day {i + 1}</option>)}</select></label><label>Time<input name="time" type="time" defaultValue="10:00" required/></label></div>}<button className="add full">{modal === 'expense' ? 'Save expense' : 'Save plan'}</button></form></div>}</div>
}
function PanelTitle({ title, description }: { title: string; description: string }) { return <div className="panel-head"><div><h2>{title}</h2><p>{description}</p></div></div> }
function ExpensePanel({ expenses, members }: { expenses: Expense[]; members: Person[] }) { return <div className="expenses"><div className="table-head"><span>EXPENSE</span><span>PAID BY</span><span>AMOUNT</span></div>{expenses.map(e => { const person = members.find(p => p.id === e.payerId)!; return <div className="expense-row" key={e.id}><div className="expense-title"><span className="expense-icon">{e.category[0]}</span><span><b>{e.title}</b><small>{e.category} · {e.date} · {e.participantIds.length} people</small></span></div><div className="payer"><Avatar person={person}/>{person.name.split(' ')[0]}</div><b>{e.currency} {e.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}</b><MoreHorizontal size={18}/></div> })}</div> }
function SettlementPanel({ lines }: { lines: { from: Person; to: Person; amount: number }[] }) { return <div className="settlement-list">{lines.length ? lines.map((line, i) => <div className="settle-person" key={i}><Avatar person={line.from}/><div><b>{line.from.name.split(' ')[0]} pays {line.to.name.split(' ')[0]}</b><small>Optimized shared-expense settlement</small></div><strong>${line.amount.toFixed(2)}</strong></div>) : <p className="empty">Everyone is settled up.</p>}<button className="settle-button"><CreditCard size={17}/>Record a payment</button></div> }
createRoot(document.getElementById('root')!).render(<App />)
